<?php


 function autoload_dfc0141f9777c098515e036aabffac63($class)
{
    $classes = array(
        'Cheetahmail\Campaigns\Campaigns' => __DIR__ .'/Campaigns.php',
        'Cheetahmail\Campaigns\Create' => __DIR__ .'/Create.php',
        'Cheetahmail\Campaigns\CampaignParams' => __DIR__ .'/CampaignParams.php',
        'Cheetahmail\Campaigns\FilterParams' => __DIR__ .'/FilterParams.php',
        'Cheetahmail\Campaigns\SentParams' => __DIR__ .'/SentParams.php',
        'Cheetahmail\Campaigns\SpeedValue' => __DIR__ .'/SpeedValue.php',
        'Cheetahmail\Campaigns\MessageParams' => __DIR__ .'/MessageParams.php',
        'Cheetahmail\Campaigns\CreateResponse' => __DIR__ .'/CreateResponse.php',
        'Cheetahmail\Campaigns\AuthHeader' => __DIR__ .'/AuthHeader.php',
        'Cheetahmail\Campaigns\CreateWithMultipleSents' => __DIR__ .'/CreateWithMultipleSents.php',
        'Cheetahmail\Campaigns\ArrayOfSentParams' => __DIR__ .'/ArrayOfSentParams.php',
        'Cheetahmail\Campaigns\ArrayOfMessageParams' => __DIR__ .'/ArrayOfMessageParams.php',
        'Cheetahmail\Campaigns\CreateWithMultipleSentsResponse' => __DIR__ .'/CreateWithMultipleSentsResponse.php',
        'Cheetahmail\Campaigns\UpdateCampaign' => __DIR__ .'/UpdateCampaign.php',
        'Cheetahmail\Campaigns\UpdateCampaignResponse' => __DIR__ .'/UpdateCampaignResponse.php',
        'Cheetahmail\Campaigns\CancelCampaign' => __DIR__ .'/CancelCampaign.php',
        'Cheetahmail\Campaigns\CancelCampaignResponse' => __DIR__ .'/CancelCampaignResponse.php',
        'Cheetahmail\Campaigns\CancelSent' => __DIR__ .'/CancelSent.php',
        'Cheetahmail\Campaigns\CancelSentResponse' => __DIR__ .'/CancelSentResponse.php',
        'Cheetahmail\Campaigns\ReprogrammCampaign' => __DIR__ .'/ReprogrammCampaign.php',
        'Cheetahmail\Campaigns\ReprogrammCampaignResponse' => __DIR__ .'/ReprogrammCampaignResponse.php',
        'Cheetahmail\Campaigns\GetCampaign' => __DIR__ .'/GetCampaign.php',
        'Cheetahmail\Campaigns\GetCampaignResponse' => __DIR__ .'/GetCampaignResponse.php',
        'Cheetahmail\Campaigns\CampaignsDetails' => __DIR__ .'/CampaignsDetails.php',
        'Cheetahmail\Campaigns\STATUS' => __DIR__ .'/STATUS.php',
        'Cheetahmail\Campaigns\ArrayOfSentDetails' => __DIR__ .'/ArrayOfSentDetails.php',
        'Cheetahmail\Campaigns\SentDetails' => __DIR__ .'/SentDetails.php',
        'Cheetahmail\Campaigns\SENTSTATUS' => __DIR__ .'/SENTSTATUS.php',
        'Cheetahmail\Campaigns\FindCampaignsByDescription' => __DIR__ .'/FindCampaignsByDescription.php',
        'Cheetahmail\Campaigns\FindCampaignsByDescriptionResponse' => __DIR__ .'/FindCampaignsByDescriptionResponse.php',
        'Cheetahmail\Campaigns\ArrayOfDetailsCamp' => __DIR__ .'/ArrayOfDetailsCamp.php',
        'Cheetahmail\Campaigns\DetailsCamp' => __DIR__ .'/DetailsCamp.php',
        'Cheetahmail\Campaigns\GetSourceByIdSent' => __DIR__ .'/GetSourceByIdSent.php',
        'Cheetahmail\Campaigns\GetSourceByIdSentResponse' => __DIR__ .'/GetSourceByIdSentResponse.php',
        'Cheetahmail\Campaigns\SourceDetails' => __DIR__ .'/SourceDetails.php',
        'Cheetahmail\Campaigns\GetSourceOfCampaign' => __DIR__ .'/GetSourceOfCampaign.php',
        'Cheetahmail\Campaigns\GetSourceOfCampaignResponse' => __DIR__ .'/GetSourceOfCampaignResponse.php',
        'Cheetahmail\Campaigns\ArrayOfSourceDetails' => __DIR__ .'/ArrayOfSourceDetails.php',
        'Cheetahmail\Campaigns\UpdateSentParams' => __DIR__ .'/UpdateSentParams.php',
        'Cheetahmail\Campaigns\UpdateSentParamsResponse' => __DIR__ .'/UpdateSentParamsResponse.php',
        'Cheetahmail\Campaigns\ListCustom' => __DIR__ .'/ListCustom.php',
        'Cheetahmail\Campaigns\ListResponse' => __DIR__ .'/ListResponse.php',
        'Cheetahmail\Campaigns\ArrayOfCampaignsListDetails' => __DIR__ .'/ArrayOfCampaignsListDetails.php',
        'Cheetahmail\Campaigns\CampaignsListDetails' => __DIR__ .'/CampaignsListDetails.php',
        'Cheetahmail\Campaigns\ListBetweenTwoDates' => __DIR__ .'/ListBetweenTwoDates.php',
        'Cheetahmail\Campaigns\ListBetweenTwoDatesResponse' => __DIR__ .'/ListBetweenTwoDatesResponse.php',
        'Cheetahmail\Campaigns\UpdateMessage' => __DIR__ .'/UpdateMessage.php',
        'Cheetahmail\Campaigns\UpdateMessageResponse' => __DIR__ .'/UpdateMessageResponse.php',
        'Cheetahmail\Campaigns\Delete' => __DIR__ .'/Delete.php',
        'Cheetahmail\Campaigns\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'Cheetahmail\Campaigns\Suspend' => __DIR__ .'/Suspend.php',
        'Cheetahmail\Campaigns\SuspendResponse' => __DIR__ .'/SuspendResponse.php',
        'Cheetahmail\Campaigns\Start' => __DIR__ .'/Start.php',
        'Cheetahmail\Campaigns\StartResponse' => __DIR__ .'/StartResponse.php',
        'Cheetahmail\Campaigns\Restart' => __DIR__ .'/Restart.php',
        'Cheetahmail\Campaigns\RestartResponse' => __DIR__ .'/RestartResponse.php',
        'Cheetahmail\Campaigns\GetTotalMailCount' => __DIR__ .'/GetTotalMailCount.php',
        'Cheetahmail\Campaigns\GetTotalMailCountResponse' => __DIR__ .'/GetTotalMailCountResponse.php',
        'Cheetahmail\Campaigns\GetCurrentMailCount' => __DIR__ .'/GetCurrentMailCount.php',
        'Cheetahmail\Campaigns\GetCurrentMailCountResponse' => __DIR__ .'/GetCurrentMailCountResponse.php',
        'Cheetahmail\Campaigns\ExecuteCampaignPreview' => __DIR__ .'/ExecuteCampaignPreview.php',
        'Cheetahmail\Campaigns\ExecuteCampaignPreviewResponse' => __DIR__ .'/ExecuteCampaignPreviewResponse.php',
        'Cheetahmail\Campaigns\CloseCampaign' => __DIR__ .'/CloseCampaign.php',
        'Cheetahmail\Campaigns\CloseCampaignResponse' => __DIR__ .'/CloseCampaignResponse.php',
        'Cheetahmail\Campaigns\DuplicateCampaign' => __DIR__ .'/DuplicateCampaign.php',
        'Cheetahmail\Campaigns\DuplicateCampaignResponse' => __DIR__ .'/DuplicateCampaignResponse.php',
        'Cheetahmail\Campaigns\AddSent' => __DIR__ .'/AddSent.php',
        'Cheetahmail\Campaigns\AddSentResponse' => __DIR__ .'/AddSentResponse.php',
        'Cheetahmail\Campaigns\ReprogramSent' => __DIR__ .'/ReprogramSent.php',
        'Cheetahmail\Campaigns\ReprogramSentResponse' => __DIR__ .'/ReprogramSentResponse.php',
        'Cheetahmail\Campaigns\DeleteSent' => __DIR__ .'/DeleteSent.php',
        'Cheetahmail\Campaigns\DeleteSentResponse' => __DIR__ .'/DeleteSentResponse.php',
        'Cheetahmail\Campaigns\DuplicateSent' => __DIR__ .'/DuplicateSent.php',
        'Cheetahmail\Campaigns\DuplicateSentResponse' => __DIR__ .'/DuplicateSentResponse.php',
        'Cheetahmail\Campaigns\UpdateSent' => __DIR__ .'/UpdateSent.php',
        'Cheetahmail\Campaigns\UpdateSentResponse' => __DIR__ .'/UpdateSentResponse.php',
        'Cheetahmail\Campaigns\UpdateSentMessage' => __DIR__ .'/UpdateSentMessage.php',
        'Cheetahmail\Campaigns\UpdateSentMessageResponse' => __DIR__ .'/UpdateSentMessageResponse.php',
        'Cheetahmail\Campaigns\StartSent' => __DIR__ .'/StartSent.php',
        'Cheetahmail\Campaigns\StartSentResponse' => __DIR__ .'/StartSentResponse.php',
        'Cheetahmail\Campaigns\RestartSent' => __DIR__ .'/RestartSent.php',
        'Cheetahmail\Campaigns\RestartSentResponse' => __DIR__ .'/RestartSentResponse.php',
        'Cheetahmail\Campaigns\SuspendSent' => __DIR__ .'/SuspendSent.php',
        'Cheetahmail\Campaigns\SuspendSentResponse' => __DIR__ .'/SuspendSentResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_dfc0141f9777c098515e036aabffac63');

// Do nothing. The rest is just leftovers from the code generation.
{
}
